### ISSUE TITLE
Keep showing An error occured! undefined

### ISSUE THREAD

**Issue by LeeFuuChang** [joeleisner/twitch-stream-check#7]
![image](https://user-images.githubusercontent.com/77952182/108622747-c6c92a00-7475-11eb-86eb-2cead77bd5e5.png)
when i tried to use the command it just keeps poping up

**Comment by joeleisner** [comment]
Hey, @edjjde - It appears that since the last time I updated this tool, Twitch's now deprecated Kraken API changed the way you query streams via a user's login name. I'll look into this, although this tool may soon be archived, as I'm not sure how much longer the Kraken API will be supported. I'll keep you posted!

**Comment by joeleisner** [comment]
Hey, @edjjde - Good news! I was able to update the CLI after researching some of the changes Twitch did to their legacy API and it's now working as expected. Please use the newly published v1.4.0 of the CLI in order to see these changes. Let me know if you have any questions or concerns!
